name: Esegui Script Python

on:
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Esegui script Python
        run: python update_somma.py

      - name: Commit e push delle modifiche
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git stash  # Salva temporaneamente le modifiche locali
          git pull --rebase  # Scarica le modifiche dal repository remoto
          git stash pop  # Ripristina le modifiche locali
          git add somma.txt
          git commit -m "Aggiornato somma.txt" --allow-empty || echo "Nessuna modifica da commitare"
          git push
