name: Controllo Circolari

on:
  schedule:
    - cron: '*/1 * * * *'  # Esegui ogni minuto
  workflow_dispatch:  # Consente di avviare manualmente

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui programma
        run: python check_circolari.py
